version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quizgame
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: quizgame_app
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/quizgame
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      PORT: 8080
    ports:
      - "8080:8080"
